name       : diffstat
version    : 1.61
release    : 8
source     :
    - ftp://invisible-island.net/diffstat/diffstat-1.61.tgz : 25359e0c27183f997b36c9202583b5dc2df390c20e22a92606af4bf7856a55ee
license    :
    - GPL-2.0
component  : system.devel
summary    : diffstat reads the output of diff and displays a histogram of the insertions, deletions, and modifications per-file.
description: |
    diffstat reads the output of diff and displays a histogram of the insertions, deletions, and modifications per-file. It is useful for reviewing large, complex patch files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
