name       : diffstat
version    : '1.63'
release    : 11
source     :
    - ftp://ftp.invisible-island.net/diffstat/diffstat-1.63.tgz : 7eddd53401b99b90bac3f7ebf23dd583d7d99c6106e67a4f1161b7a20110dc6f
license    : MIT
component  : system.devel
summary    : diffstat reads the output of diff and displays a histogram of the insertions,
    deletions, and modifications per-file
description: |
    diffstat reads the output of diff and displays a histogram of the insertions, deletions, and modifications per-file. It is useful for reviewing large, complex patch files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
